Repository cloudify-cosmo/cloudify-ui-common, pull requests merged in 2022-11, with the labels that each got.

#145 RD-5228 Cypress 10 upgrade
  package-lock.json
  packages/cypress/.gitignore
  packages/cypress/cypress.json
  packages/cypress/package.json
  packages/cypress/src/config/index.ts
  packages/cypress/src/config/typings.d.ts
  packages/cypress/src/plugins/index.ts
  packages/cypress/src/plugins/setRemovingVideosForPassedTestsTask.ts
  packages/cypress/src/support/index.ts
Labels: internal

#146 RD-5228 Fix code coverage setup
  packages/cypress/src/config/index.ts
  packages/cypress/src/support/index.ts
Labels: internal

#147 RD-6280 Resolved loader-utils vulnerability
  package-lock.json
Labels: dependencies

#148 RD-6398 fix audit for loader-utils
  package-lock.json
Labels: bug-fix

#149 RD-5881 update types/nodes to v16.11.68
  package-lock.json
  packages/backend/package.json
Labels: internal
