Repository cloudify-cosmo/cloudify-ui-common, pull requests merged in 2022-07, with the labels that each got.

#125 RD-5340: Resolved sequalize package vulnerability
  package-lock.json
Labels: dependencies

#126 RD-2855: Create common ESLint configuration for Jest
  .eslintrc.json
  configs/README.md
  configs/eslint-common-jest.json
Labels: feature

#129 RD-5435 Bump `sequelize` package to v6.21.3
  backend/package.json
  package-lock.json
  package.json
Labels: dependencies, bug-fix
