Repository cloudify-cosmo/cloudify-ui-common, pull requests merged in 2022-03, with the labels that each got.

#76 RD-1290 Migration of backend directory to TypeScript
  .gitignore
  backend/.eslintrc.json
  backend/db.ts
  backend/index.js
  backend/index.ts
  backend/logger.ts
  backend/migration.ts
  backend/package.json
  backend/test/.eslintrc.json
  backend/test/db.test.ts
  backend/test/logger.test.ts
  backend/test/migration.test.ts
  backend/test/toMock.ts
  backend/tsconfig.json
  jest.config.js
  package-lock.json
  package.json
Labels: breaking-change, internal

#103 RD-1962: Migrate npm to the 8th version
  package-lock.json
Labels: dependencies, internal

#102 RD-3119 Improve backend code to allow full migration of DB models and migration scripts to TS
  backend/index.ts
  backend/migration.ts
  package-lock.json
  package.json
Labels: dependencies, breaking-change

#109 RD-4447 Fix logger call in migration script
  backend/migration.ts
Labels: bug-fix

#107 RD-2561 Remove `run-system-tests.sh` script
  package-lock.json
  package.json
  scripts/README.md
  scripts/run-system-tests.sh
Labels: breaking-change

#111 RD-4450 Fix Patroni URL requests in DB module
  backend/db.ts
  backend/test/db.test.ts
Labels: bug-fix

#112 RD-3155 Add script to get TS migration progress
  scripts/README.md
  scripts/get-ts-migration-progress.sh
Labels: feature

#114 RD-4051: Providing the script for loading the latest premium docker dev image
  scripts/README.md
  scripts/load-latest-premium-docker-image.sh
Labels: internal
