Repository cloudify-cosmo/cloudify-ui-common, pull requests merged in 2022-02, with the labels that each got.

#92 RD-4050 Add description about Internal section used in UI packages release notes
  README.md
Labels: internal

#93 RD-2570 Removing videos for cypress passed tests
  cypress/src/plugins/index.ts
  cypress/src/plugins/setRemovingVideosForPassedTestsTask.ts
Labels: internal

#90 RD-3222 Disable agreed to disable ESLint rules globally
  configs/eslint-common-react.json
  configs/eslint-common.json
Labels: internal

#96 RD-4049 Update GitHub Pull Request template
  .github/pull_request_template.md
Labels: internal

#97 RD-2544 Remove unused CircleCI configuration
  .circleci/config.yml
Labels: internal

#98 RD-3222 Improve relationships between ESLint configs
  .eslintrc.json
  backend/.eslintrc.json
  configs/README.md
  configs/eslint-common-cypress.json
  configs/eslint-common-node.json
  configs/eslint-common-react.json
  configs/eslint-common.json
Labels: feature

#99 RD-3609 Fix security audit issue coming from vulnerable `request` package
  package-lock.json
Labels: dependencies, internal

#100 RD-3353 Upgraded umzug to v3
  backend/migration.js
  backend/test/migration.test.js
  package-lock.json
  package.json
Labels: internal

#95 RD-1289: Migrate src directory to typescript
  backend/README.md
  backend/documentation.yml
  ci/verify-docs.sh
  documentation.yml
  jenkins/Jenkinsfile
  package-lock.json
  package.json
  rollup.config.js
  src/README.md
  src/consts.ts
  src/icons.ts
  src/index.js
  src/index.ts
  src/types.ts
  test/icons.test.ts
Labels: internal

#101 RD-382 Moved form request to axios
  backend/db.js
  backend/test/db.test.js
  package-lock.json
  package.json
Labels: internal
